<?php
/**
 * Implemnts hook_menu().
 */
function editinline_menu() {
  $items['editinline/save'] = array(
    'title' => '', 
    'page callback' => 'editinline_save', 
    'access arguments' => array('administer content'), 
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback fot AJAX call. 
 */
function editinline_save() {
  $content = $_POST['content'];
  $qs = explode("/", $_POST['q']); 
  $node = node_load($qs[1]);
  $node->title = $content;
  node_save($node);
  print isset($node->nid);
}

/**
 * Implemnts hook_node_view().
 */
function editinline_node_view($node, $view_mode, $langcode) {
  if (node_access("update", $node)) {
    drupal_add_js(drupal_get_path('module', 'editinline') . '/editinline.js');
    drupal_add_css(drupal_get_path('module', 'editinline') . '/editinline.css');
  }
}